# Generated by Django 4.2.4 on 2023-08-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_image_member_image_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='member',
            name='location',
        ),
        migrations.RemoveField(
            model_name='member',
            name='room',
        ),
        migrations.AddField(
            model_name='member',
            name='material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
