# Generated by Django 4.2.4 on 2023-08-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_member_bathroom_remove_member_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='property_name',
            new_name='productName',
        ),
    ]
